version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5001:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
    networks:
      - dbnet
    
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-server2
    environment:
      MYSQL_DATABASE: tooling
      MYSQL_USER: Willie
      MYSQL_PASSWORD: Password123
      MYSQL_RANDOM_ROOT_PASSWORD: Password123
    volumes:
      - db:/var/lib/mysql
    networks:
      - dbnet
volumes:
  tooling_frontend:
  db:

networks:
  dbnet:
    driver: bridge